export const Users = [
  {
    id: 1,
    first_name: "Emiline",
    last_name: "McClune",
    email: "emcc00@xrea.com",
    gender: "Female",
  },
  {
    id: 2,
    first_name: "Felix",
    last_name: "Ingleston",
    email: "finglex@hibh.com",
    gender: "Female",
  },
  {
    id: 3,
    first_name: "Travus",
    last_name: "Bergstram",
    email: "tbergstream@xrea.com",
    gender: "Female",
  },
  {
    id: 4,
    first_name: "Celinda",
    last_name: "Sharvill",
    email: "csharvill@narod.com",
    gender: "Female",
  },
  {
    id: 5,
    first_name: "Annie",
    last_name: "Cockaye",
    email: "accokyme@hibu.com",
    gender: "Male",
  },
  {
    id: 6,
    first_name: "Lamod",
    last_name: "Ricket",
    email: "lricket700@hibu.com",
    gender: "Male",
  },
  {
    id: 7,
    first_name: "Ellish",
    last_name: "Perry",
    email: "eperu00@hibu.com",
    gender: "Female",
  },
  {
    id: 8,
    first_name: "Ellish",
    last_name: "Perry",
    email: "eperu00@hibu.com",
    gender: "Female",
  },
  {
    id: 9,
    first_name: "Corina",
    last_name: "Chipping",
    email: "cchipping@biblegateway.com",
    gender: "Female",
  },
  {
    id: 10,
    first_name: "Dorel",
    last_name: "Trewhite",
    email: "dtrewhite@trellian.com",
    gender: "Male",
  },
  {
    id: 11,
    first_name: "Chaddy",
    last_name: "Catonne",
    email: "ccatonek@sohu.com",
    gender: "Female",
  },
  {
    id: 12,
    first_name: "Pete",
    last_name: "Landa",
    email: "plandaoy@4shared.com",
    gender: "Male",
  },
  {
    id: 13,
    first_name: "Murial",
    last_name: "Calliss",
    email: "mcallissow@mediafire.com",
    gender: "Male",
  },
  {
    id: 14,
    first_name: "Abul",
    last_name: "Obbard",
    email: "obbardox@woothemes.com",
    gender: "Male",
  },
  {
    id: 15,
    first_name: "Zaral",
    last_name: "ul-Haq",
    email: "crownedzar@globalstates.com",
    gender: "Male",
  },
  {
    id: 16,
    first_name: "Timofei",
    last_name: "koi",
    email: "koitimo@mitedu.com",
    gender: "Female",
  },
];
